import { Relationship, WorkItem, KPIStats } from '../types/index.ts';

export const initialRelationships: Relationship[] = [
  {
    id: 'rel-1',
    name: 'Ahmed El-Mansy',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    company: 'Orascom Construction',
    location: 'Cairo | Egypt',
    starred: true,
    score: 78,
    status: 'Hot',
    commercialGoal: 'Receive RFQ',
    currentStage: 'Solution Alignment',
    suggestedChannel: 'email',
    nextBestAction: 'Send quotation with customized pricing and case study.',
    aiConfidence: 85,
    tags: ['Metro Project', 'Decision Maker', 'Budget Holder'],
    whyToday: 'Ahmed requested pricing for the Metro Line 6 project yesterday. You committed to sending the quotation today. Timely response will strengthen trust and move the relationship forward.'
  },
  {
    id: 'rel-2',
    name: 'Sarah Patel',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    company: 'Larsen & Toubro',
    location: 'Mumbai | India',
    starred: false,
    score: 84,
    status: 'Hot',
    commercialGoal: 'Schedule Technical Review',
    currentStage: 'Trust Building',
    suggestedChannel: 'linkedin',
    nextBestAction: 'Provide updated project timeline and engineering blueprints.',
    aiConfidence: 92,
    tags: ['EPC Bid', 'Engineering Lead', 'Key Influencer'],
    whyToday: 'Sarah liked your recent LinkedIn update on urban transit. It is a perfect micro-moment to transition into a project timeline follow-up for the upcoming bid.'
  },
  {
    id: 'rel-3',
    name: 'Ravi Menon',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    company: 'DMRC',
    location: 'Delhi | India',
    starred: false,
    score: 65,
    status: 'Warm',
    commercialGoal: 'Demo Approval',
    currentStage: 'Solution Alignment',
    suggestedChannel: 'whatsapp',
    nextBestAction: 'Offer a short hands-on sandbox environment access link.',
    aiConfidence: 76,
    tags: ['Procurement', 'Delhi Metro', 'Technical Committee'],
    whyToday: 'Ravi mentioned his team is evaluating three different solution providers this week. Sending a sandbox workspace link right now gives them immediate, frictionless access.'
  },
  {
    id: 'rel-4',
    name: 'James Kim',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    company: 'Hyundai Engineering',
    location: 'Seoul | South Korea',
    starred: false,
    score: 72,
    status: 'Stable',
    commercialGoal: 'Finalize MSA',
    currentStage: 'Trust Building',
    suggestedChannel: 'email',
    nextBestAction: 'Follow up on redlines sent by legal last Wednesday.',
    aiConfidence: 89,
    tags: ['Legal Review', 'Executive Sponsor', 'Seoul HQ'],
    whyToday: 'Hyundai legal has held the redlined MSA for over 6 business days. A gentle, executive-to-executive nudge is required to unblock the procurement timeline.'
  },
  {
    id: 'rel-5',
    name: 'Laura Anderson',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
    company: 'JLL',
    location: 'Dubai | UAE',
    starred: false,
    score: 58,
    status: 'Stable',
    commercialGoal: 'Expand Account',
    currentStage: 'Recognition',
    suggestedChannel: 'linkedin',
    nextBestAction: 'Share regional commercial real-estate expansion report.',
    aiConfidence: 68,
    tags: ['Real Estate', 'Dubai Marina', 'Regional VP'],
    whyToday: 'JLL Dubai just announced their Q2 retail vacancy results. Sending our latest analysis report position you as an expert advisor rather than a service seller.'
  },
  {
    id: 'rel-6',
    name: 'Miguel Silva',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    company: 'Metro de Madrid',
    location: 'Madrid | Spain',
    starred: false,
    score: 69,
    status: 'Warm',
    commercialGoal: 'Secure Introduction',
    currentStage: 'Introduction',
    suggestedChannel: 'email',
    nextBestAction: 'Introduce yourself and share our previous Madrid light rail case study.',
    aiConfidence: 82,
    tags: ['Europe Transit', 'New Account', 'Director of Operations'],
    whyToday: 'Miguel recently assumed the operations leadership role. Reaching out with a warm congratulations and light rail case study is highly contextual and respectful.'
  },
  {
    id: 'rel-7',
    name: 'Fatima Al-Hashimi',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    company: 'Etihad Rail',
    location: 'Abu Dhabi | UAE',
    starred: true,
    score: 91,
    status: 'Hot',
    commercialGoal: 'Nurture Executive Stakeholder',
    currentStage: 'Recognition',
    suggestedChannel: 'whatsapp',
    nextBestAction: 'Send friendly weekend greeting and inquire about Abu Dhabi summit.',
    aiConfidence: 95,
    tags: ['VIP Client', 'Abu Dhabi', 'Board Member'],
    whyToday: 'Fatima is speaking at the Middle East Rail Summit in Abu Dhabi tomorrow. Sending a support message and wishing her success strengthens your close peer-level connection.'
  }
];

export const initialWorkItems: WorkItem[] = [
  {
    id: 'work-1',
    relationshipId: 'rel-1',
    relationship: initialRelationships[0],
    category: 'commitment',
    description: 'Quotation promised yesterday',
    priority: 'High',
    dueTime: '09:30 AM',
    channel: 'email',
    completed: false,
    starred: false
  },
  {
    id: 'work-2',
    relationshipId: 'rel-2',
    relationship: initialRelationships[1],
    category: 'commercial',
    description: 'Follow up on proposal',
    priority: 'High',
    dueTime: '10:15 AM',
    channel: 'linkedin',
    completed: false,
    starred: false
  },
  {
    id: 'work-3',
    relationshipId: 'rel-3',
    relationship: initialRelationships[2],
    category: 'commercial',
    description: 'Product demo follow up',
    priority: 'Medium',
    dueTime: '11:00 AM',
    channel: 'whatsapp',
    completed: false,
    starred: false
  },
  {
    id: 'work-4',
    relationshipId: 'rel-4',
    relationship: initialRelationships[3],
    category: 'building',
    description: 'Contract discussion',
    priority: 'Medium',
    dueTime: '11:30 AM',
    channel: 'email',
    completed: false,
    starred: false
  },
  {
    id: 'work-5',
    relationshipId: 'rel-5',
    relationship: initialRelationships[4],
    category: 'nurture',
    description: 'Check-in and nurture',
    priority: 'Low',
    dueTime: '01:00 PM',
    channel: 'linkedin',
    completed: false,
    starred: false
  },
  {
    id: 'work-6',
    relationshipId: 'rel-6',
    relationship: initialRelationships[5],
    category: 'building',
    description: 'Introduction follow up',
    priority: 'Medium',
    dueTime: '02:30 PM',
    channel: 'email',
    completed: false,
    starred: false
  },
  {
    id: 'work-7',
    relationshipId: 'rel-7',
    relationship: initialRelationships[6],
    category: 'nurture',
    description: 'Periodic check-in',
    priority: 'Low',
    dueTime: '03:15 PM',
    channel: 'whatsapp',
    completed: false,
    starred: false
  }
];

export const mockKPIStats: KPIStats = {
  todayMission: 87,
  estFocusTime: '2h 15m',
  advanceCount: 23,
  replyRate: '42%'
};
